# Generated by Django 6.0.1 on 2026-01-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_city_name_en_city_name_ru_property_address_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
